// Code Generated by Sidekick is for learning and experimentation purposes only.
import * as dotenv from 'dotenv';
dotenv.config();

export const config = {
  baseURL: process.env.BASE_URL || 'https://qtopportalweb.aaps.deloitte.com/',
  username: process.env.USERNAME || 'LEFAHTest1006@deloitte.com',
  password: process.env.PASSWORD || 'RexR)7t>%80v#ZhzX',
};

